[package]
name = "snakes-and-ladders"
version = "0.1.0"
authors = ["Lauri Virtanen <lauri.virtanen@iki.fi>"]
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
rand = "0.8.5"
